### ISSUE TITLE
Location of outputs folder

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#104]
Cannot have this be in the root path for dynasim, because this conflicts when doing `git add *`:

`The following paths are ignored by one of your .gitignore files:`
`outputs`

Moved outputs back to demos folder in commit 195f3f55fe9cf229c16f25e2718a61260dee7665

@benpolletta , I'm undoing this change for now, but if you can find a work around to fix this, please do! (and undo this commit)

**Comment by davestanley** [comment]
I put the outputs folder back in DynaSim/outputs for the sake of convenience.

However, I get the following error when running `git add *`

Does anyone know how to bypass this? @erikthered12 @asoplata 

> $ git add *
> The following paths are ignored by one of your .gitignore files:
> outputs
> Use -f if you really want to add them.
>

**Comment by erik-roberts** [comment]
what is the goal here? are you trying to have outputs not accidentally sync to github, or are you having outputs be easier to find? if its demo-related outputs, it seems like that should stay in demos.

**Comment by davestanley** [comment]
It was about (A) not syncing, (B) easier to find, and (C) common location for all dynasim outputs. For example the demos_xPlt.m demo is currently in the dependencies/MDD folder, not the demos folder (I am keeping it there to allow it to stay in sync with commits to the MDD repo, although on second thought perhaps this is not so important since it seems Git automatically saves the head location in MDD with each commit to DynaSim).

So I'm 50/50 here. I believe @benpolletta originally moved the location of the outputs folder so you migth want to check with him

**Comment by erik-roberts** [comment]
to answer the bypass question, one simply removes outputs from .gitignore.

**Comment by benpolletta** [comment]
Heyo,

As far as I can recall, I was moving the outputs folder to the DynaSim
directory because I was getting an error due to DynaSim finding
demo_sPING_3b in the path even when it didn't exist in the current
directory, and so not creating it. Thus, I wanted demos to find the outputs
folder inside DynaSim, where demo_sPING_3b exists. Looking back on this, it
seems like a very hacky solution to a problem that I think Dave has fixed (
d572d70
<https://github.com/DynaSim/DynaSim/commit/d572d7047f483923d4ef56aef3a6dcc710fe0935>
).

Dave, if you *don't* want the outputs folder to sync with DynaSim, then it
seems like we're getting the behavior we want, and it's fine to have it in
your .gitignore file. You'll just have to find another way to use git add -
i.e., git add *.m - that doesn't attempt to add the outputs directory. Does
that seem correct?

B

**Comment by erik-roberts** [comment]
This error is just a warning afaik, that doesn't affect anything.

```
The following paths are ignored by one of your .gitignore files:
outputs
```

**Comment by benpolletta** [comment]
It doesn't actually let you add anything, from what I recall.

**Comment by erik-roberts** [comment]
i must have gotten a similar but different message then when i did `git add all`

**Comment by erik-roberts** [comment]
Move it to ~/Documents/DynaSimData

**Comment by davestanley** [comment]
Working on this now

**Comment by davestanley** [comment]
Finished

**Comment by davestanley** [comment]
See also #103

**Comment by davestanley** [comment]
Error when using `isfunction`
>> cd ~/src/DynaSimSherfey/demos
Undefined function or variable 'isfunction'.
Error in setupDynaSimPath (line 7)
if ~isfunction('SimulateModel')                                                 % If DynaSim not in path...
