### ISSUE TITLE
Working with spike times

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#133]
mech file that stores last spike time

**Comment by asoplata** [comment]
Is this implemented, or is there any current way to access (at runtime) whether there was a spike or not? E.g. @jsherfey Is there a current way to access if there was a spike in the previous/current timestep?

**Comment by davestanley** [comment]
I still haven't had a chance to implement this in DynaSim. However, here is the code from my DNSim implementation! 

https://github.com/davestanley/dnsim-database-additions/blob/master/iSYNdualexp

To do:
1) It is not 100% stable (e.g. certain voltage transients can cause it to explode)
2) Convert to DynaSim

At its core, you can see how it works here: 

```
% ODEs
            % Each ODE variables s1..s5 track the time since the 1st..5th spikes
            % It rises to the total desired time, smax, and then decays
            % linearly to 0, at which point the PSP has passed)
s1' = (smax*(smax-s1)/tauR).*(1+tanh(IN/10))*(s2 < 1) - 1/dt*(s1 > 0);  % s1 can only rise if s2 is off
s2' = (smax*(smax-s2)/tauR).*(1+tanh(IN/10))*(s3 < 1) - 1/dt*(s2 > 0);  % s2 can only rise if s3 is off
s3' = (smax*(smax-s3)/tauR).*(1+tanh(IN/10))*(s4 < 1) - 1/dt*(s3 > 0);  % s3 can only rise if s4 is off
s4' = (smax*(smax-s4)/tauR).*(1+tanh(IN/10))*(s5 < 1) - 1/dt*(s4 > 0);  % s4 can only rise if s5 is off
s5' = (smax*(smax-s5)/tauR).*(1+tanh(IN/10)) - 1/dt*(s5 > 0);           % s5 will saturate (maximum of 5 spikes before saturating; increase if needed)
```

State variables s1...s5 all start at zero and track at most smax ms in history. When a spike comes, it pushes s1 up to smax (default 20 ms). Then, smax will decay back to zero at a rate of 1.0 per ms. Thus, you can get the elapsed time since the previous spike by taking smax-s1.

This is how we approximate the convolution:

```
f = @(t) 1*(exp(-(t)/tauDx) - exp(-(t)/tauRx));

% Functions
ISYN(V,s) = (gsyn.*(netcon*(f(smax-s1) + f(smax-s2) + f(smax-s3) + f(smax-s4) + f(smax-s5))).*(V-Esyn))
```

If a 2nd spike arrives before s1 has returned to 0, then this is stored in ode variable s2, and so on. Thus, the system can store at most 5 spikes in "memory", occurring at most smax in the past (default 20 ms)

**Comment by davestanley** [comment]
Actually, here are some more recent versions. I think that earlier version had some issues...

[B_B_iSYNdualexp2.txt](https://github.com/DynaSim/DynaSim/files/1034522/B_B_iSYNdualexp2.txt)

[iSYNdualexp2.txt](https://github.com/DynaSim/DynaSim/files/1034523/iSYNdualexp2.txt)

**Comment by jsherfey** [comment]
DynaSim now records the previous 2 spike times whenever the spike monitor is on (e.g., using: monitor V.spikes(thresh)). Spike times can be accessed using the reserved variables "tspike" for the parent population, "tspike_pre" for presynaptic spike times, and "tspike_post" for postsynaptic spike times (equivalent to "tspike" in this case). tspike has dimensions [buffer_size x num_cells]; therefore, operations like summation can be performed on functions of spike times like this: sum(f(t-tspike)) where f is some function that, in this case, has a single argument that is the elapsed time since the previous spike.

**Comment by erik-roberts** [comment]
added to wiki https://github.com/DynaSim/DynaSim/wiki/Frequently-Asked-Questions
