### ISSUE TITLE
Allow node or population name

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#135]
modify the CheckSpec

**Comment by jsherfey** [comment]
Let's also add support for "link" instead of "connections". So,

s.node.name='E'
s.link.direction='E->E'

would be equivalent to

s.populations.name='E'
s.connections.direction='E->E'

I would recommend using "node" and "link" together OR "populations" and "connections" because those combos look better in monospaced fonts like Courier New. However, any combo should work.

Note:

The more concise
  s.pops.name='E'
  s.cons.direction='E->E'
is already supported.

**Comment by jsherfey** [comment]
This was resolved in commit 7fc7b77d6ce16ecc77144f0db7840cd543935567.

"links" and "edges" are now supported as aliases to "connections".
"nodes" is supported as alias to "populations".

**Comment by erik-roberts** [comment]
@jsherfey I don't think this has been documented (ie the 3 options). where should it go? perhaps wiki and tutorial?
