### ISSUE TITLE
Rename functions

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#136]
GetSolveFile should be WriteSolveFile

**Comment by benpolletta** [comment]
All lowercase utility functions should be changed to camelCase.

**Comment by asoplata** [comment]
Can we also make all "core"/main functions in `camelCase` style, but with the first letter lowercase? Please? This will make autocomplete much easier to use -- since EVERYONE should be using autocomplete whenever possible, since it reduces typing errors!

**Comment by erik-roberts** [comment]
i agree

**Comment by davestanley** [comment]
I am still getting bugs here, such as below. I've cleared up a few of them with the following commit bbfa245


```
Cannot find an exact (case-sensitive) match for 'checkOptions'

The closest match is: CheckOptions in /Users/davestanley/Dropbox/git/DynaSimSherfey/functions/CheckOptions.m

Error in ImportData (line 62)
options=checkOptions(varargin,{... 
```

**Comment by davestanley** [comment]
Also... why is CheckOptions not camel case? Is not this a "core" function?

**Comment by davestanley** [comment]
Never mind the above comment. Did you mass-rename all the function calls without yet renaming the actual functions? This is very confusing! If these re-names were intentional, please revert my earlier commit bbfa245.

In general, can we all agree not merge any changes into dev unless they are at least SEMI working? Right now these renames seem to have broken pretty much everything, including all code in demos.m. These changes should have been done in their own branch (both the bulk file renames plus the bulk find/replace of funciton calls) and then merged into dev as a pair.

**Comment by erik-roberts** [comment]
sorry. i finished this in a new branch and it's waiting in a pull request.

**Comment by erik-roberts** [comment]
i see why branches are ideal now.  its much easier to git revert a branch merge than doing a git reset and fixing later merges.
