### ISSUE TITLE
Mech Files

### ISSUE THREAD

**Issue by benpolletta** [DynaSim/DynaSim#170]
What goes where? What variable names can be used?
Possible solutions:
- Make a mech template. Or two: one for synapses, one for intrinsic currents.
- Make mech files into functions?
- Make a function that creates mech files using structured input?

**Comment by jsherfey** [comment]
- Mech files should not be functions. They are sets of equations, identical to the equations specified in a string specification or spec.pops.equations.
- Any variable names can be used internally.
- State variables defined in population equations can be used in the mechanism; the first state variable in the population equations can be accessed with the alias "X".
- Mechanisms can be defined in scripts without using external files. External files can be generated using DynaSim GUI. Any mechanism equations defined in script can be manually copied to a text editor and saved with name.mech; no function is required because the "structure" (i.e., list of equations) is identical.
