### ISSUE TITLE
Move code files to their own directory

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#21]
We should move code files, including MATLAB functions, bash scripts, and anything else that's actual source code, into a specific directory for source code, e.g. `src`.
- This is helpful because it 
  - cleans up the root directory of the repo, making it easy for people to not worry about the details, 
  - clearly delineates what is code from examples, etc.,
  - is useful for the Sphinx documentation as all code documentation can therefore become known as `src.SimulateModel()` for example (you'll see what I mean when I start committing what I have for the auto document generation!)

TODO:
- Doing this requires that we test to make sure all the source code is independent of any relative-to-models/demos/etc.-path code -- in other words, make sure that the source code doesn't rely on its own path/position relative to other directories.
  - I will TRY to do this, but the only way to make sure is to have @jsherfey look at my pull requests, or indicate if he has knowledge that the source code file location doesn't matter.

**Comment by DynaSim** [comment]
We will need to be careful with this. The following make assumptions about the location of files:
- `LocateModelFiles` currently assumes that it is stored in the same directory as all other DynaSim functions AND that the "models" directory is located at the same level in the directory tree. This function `LocateModelFiles` is used, for instance, by `GenerateModel` to locate mechanism files and by `CreateBatch` to generate a list of paths to be set at the beginning of each cluster job.
- `SimulateModel` starts by checking that the directory it is stored in is present in the Matlab path; if it is not already in the current Matlab path, it is added to it. This is necessary because, depending on the selected options, the current directory may be temporarily changed, then other DynaSim functions called; that would produce an error if the DynaSim functions directory was not present in the path.

These would not be problems if all the DynaSim directories were already present in the Matlab path. However, it should be sufficient for users to simply run `SimulateModel` from the directory containing it and everything work. 

One solution might be: keep `SimulateModel` in the top-level directory and have it automatically add its directory and all subdirectories to the path. That could be done very easily by changing line 358 in `SimulateModel` to: `addpath(genpath(dynasim_path));`. All other functions could then be stored in a "src" or "functions" directory and everything else left as is.

I like this solution because (1) it cleans everything up and (2) makes it clear what function the user should use (i.e., the "entry point" into DynaSim: `SimulateModel`, which is used for almost everything). If we take this approach, we might want to consider leaving the primary plotting function at the top-level directory as well: `PlotData`; that function has been designed to accept and plot DynaSim data structures at any stage of the workflow, containing results from any number of simulations, varying any number of parameters, and with any number of populations. Together, 90% of everything all users will do can be accomplished by `SimulateModel` and `PlotData`; for that reason, it might make more sense to keep those two functions more visible than the others. The entire demos script uses mainly those two functions, as well as `ImportData` and `LocateModelFiles`; the latter two could be stored in the "functions" subdirectory with the others or at the top-level directory.

**Comment by jsherfey** [comment]
We will need to be careful with this. The following make assumptions about the location of files:
- `LocateModelFiles` currently assumes that it is stored in the same directory as all other DynaSim functions AND that the "models" directory is located at the same level in the directory tree. This function `LocateModelFiles` is used, for instance, by `GenerateModel` to locate mechanism files and by `CreateBatch` to generate a list of paths to be set at the beginning of each cluster job.
- `SimulateModel` starts by checking that the directory it is stored in is present in the Matlab path; if it is not already in the current Matlab path, it is added to it. This is necessary because, depending on the selected options, the current directory may be temporarily changed, then other DynaSim functions called; that would produce an error if the DynaSim functions directory was not present in the path.

These would not be problems if all the DynaSim directories were already present in the Matlab path. However, it should be sufficient for users to simply run `SimulateModel` from the directory containing it and everything work. 

One solution might be: keep `SimulateModel` in the top-level directory and have it automatically add its directory and all subdirectories to the path. That could be done very easily by changing line 358 in `SimulateModel` to: `addpath(genpath(dynasim_path));`. All other functions could then be stored in a "src" or "functions" directory and everything else left as is.

I like this solution because (1) it cleans everything up and (2) makes it clear what function the user should use (i.e., the "entry point" into DynaSim: `SimulateModel`, which is used for almost everything). If we take this approach, we might want to consider leaving the primary plotting function at the top-level directory as well: `PlotData`; that function has been designed to accept and plot DynaSim data structures at any stage of the workflow, containing results from any number of simulations, varying any number of parameters, and with any number of populations. Together, 90% of everything all users will do can be accomplished by `SimulateModel` and `PlotData`; for that reason, it might make more sense to keep those two functions more visible than the others. The entire demos script uses mainly those two functions, as well as `ImportData` and `LocateModelFiles`; the latter two could be stored in the "functions" subdirectory with the others or at the top-level directory.

**Comment by asoplata** [comment]
Hey Jason, can you please indicate which commit closes which issues? For
the future when we want to look back at a closed issue, you can just say
something like "Resolve #21" in the commit message and github will
automatically interpret that when it's merged into master

**Comment by DynaSim** [comment]
Good to know! Thanks, will do.

**Comment by asoplata** [comment]
- Re: `LocateModelFiles`, do you mean the function assumes this path shape:

- dynasim
    - models  <models must be at this level?>
    - functions/LocateModelFiles.m

The location, and possibly many locations, of where the models are stored is something worth discussing in #20 

Two things:

1. I interpret whether or not the DynaSim code is on the path as part of the installation; having `SimulateModel` work out of the box is fine, but **there should be a recommended installation procedure** and by recommended I mean really really recommended. There are many reasons, but making it easier to help people trying to get onboard or debug just getting DynaSim in the first place is reason alone for doing this. Even if it's as simple as "make sure you add the DynaSim directory and all its subdirectories to the MATLAB path."

2. I really really really think that the files/directory hierarchy should NOT be a part of trying to teach how to use DynaSim. I understand the reason for putting the functions there, and I don't really care that they're there (although I think if someone wanted to use other plotting functions it could start to get complicated). My main point is that teaching the user which functions they're supposed to use  should **only be done by the docs** in the form of tutorials, getting started guides, etc., NOT the overall makeup of the directory structure. I would rather treat them equivalently to all other functions, keep them all in the same place, and instead use only the documentation to instruct which functions to learn to use (I think everyone agrees on this last point), etc., but whatever. I just don't think we should teach the directory structure as any part of learning how to use it -- that's my point.
    1. Subquestion: what is the expected development of `PlotData`? Is the future expectation that everyone will develop better analysis tools that all hook in to that one? If someone wants to do their own plotting using different code, are they expected to wire that into `PlotData`?
    2. If `SimulateModel` and `PlotData` are at the highest level, then at what point do I run my analysis scripts (without plotting)? I may want to run a big analysis over many jobs (in a distributed way) that'll take all night -- in the future shouldn't there be a third major user function for that?

**Comment by asoplata** [comment]
Really good new reason for keeping all functions in the same folder: **I think the MATLAB domain filter we have to use for Sphinx only works if all your code is in a single source directory -- therefore I think all functions like `SimulateModel` should be contained in a single directory.** I can't get it to work any other way -- it seems to work by co-opting Sphinx's interpretation of Python "modules" by counting the MATLAB file source directory as a single module, and assuming all files are in there. 

Similarly, I think the MATLAB Sphinx extension also forces the name of the "module" that all the functions are classified under to be the same as the directory name containing them all -- so currently, all functions in the documentation read like `functions.AnalyzeData(data,func...` because the name of the directory is `functions`. I think this is also unavoidable, or at least I can't figure out how to change it. **Therefore, I think we should also change the name of the directory containing the functions to be as small as possible, like `src`.**

Very soon I'm going to commit on branch iss0017... so that everyone will have what they need to build the documentation, and to see it.

**Comment by asoplata** [comment]
See e966e277 for a how-to guide on building the documentation, and https://github.com/DynaSim/DynaSim/blob/iss0017_docu_std/docs/_build/html/index.html for an example of how the documentation will look.

**Comment by asoplata** [comment]
Pasted from an email from Jason: "Good points about keeping all functions together (issue 21), especially if that's necessary for automating documentation creation." So I'm taking from that that Jason agrees with my points, and that we should move `SimulateModel.m` and `PlotData.m` back into `functions/`

**Comment by asoplata** [comment]
Since #18 has changed, I'd like to update this as well. In order to build all documentation into a git-tracked "docs" folder for use with GitHub Pages, we still need to move all core functions into their own directory. In other words, this still needs to be done, and done with care. But judging from this thread's lack of rejection and the email I mentioned above with Jason, I'm assuming **we're good to go with moving `SimulateModel.m` and `PlotData.m` into the `functions` folder**. I still stand by my previous comments that new users should learn from DOCUMENTATION like the demos and tutorial, NOT from the structure of the files in the repo.

**Comment by asoplata** [comment]
This was done in the above commit.
