### ISSUE TITLE
findpeaks

### ISSUE THREAD

**Issue by erikthered12** [DynaSim/DynaSim#31]
findpeaks in calcPower overlaps with Chronux.

**Comment by asoplata** [comment]
Do you mean Chronux also has a function with that name? I don't have Chronux installed, but `findpeaks()` and everything else works fine, I think that DynaSim is instead using [the `findpeaks` from the Signal Processing Toolbox](https://www.mathworks.com/help/signal/ref/findpeaks.html). 

Given that Chronux is an additional install not required by DynaSim, I think the onus should be on specifying the overlapping Chronux functions in the namespace, rather than overwriting the built-in Signal Toolbox's. IIRC this is as easy as saying `chronux.whatever.findpeaks`, but I can't remember. I'm not sure how much help MATLAB gives you in specifying namespaces, but I think it gives you enough for this.

(From what I can tell, Chronux had a function by that name FIRST (Chronux started in 2001? while the Signal Toolbox's function claims it's from 2007), but then MATLAB introduced a function of the same name. So Chronux gets firsties in terms of being right, but they're third-party so unfortunately I see it as they need to compensate.)

**Comment by erikthered12** [comment]
i just had my code remove chronux from the path before calling the plotting functions

**Comment by asoplata** [comment]
In thinking more about this issue, I've determined that DynaSim is set up to use the Digitial Signal Processing Toolbox's `findpeaks()` NOT Chronux's. Chronux's `findpeaks()` only accepts two arguments `data` and `threshold`, while DynaSim's `findpeaks()` call uses additional arguments `MinPeakHeight` and `NPeaks`. Therefore, DS uses the DSP `findpeaks()`.

Unfortunately, this also implies that adding Chronux to the top of your MATLAB path, as is its proper installation, will cause DS' `CalcFR()` to stop working correctly.

This MAY be rectified by adding Chronux to the BOTTOM of your MATLAB path, but I doubt it -- if other Chronux functions depend on Chronux' specific `findpeaks()`, then those Chronux functions will also break, since you will be using the DSP's `findpeaks()`.

From a cursory StackOverflow look, there doesn't seem to be an easy, built-in way in MATLAB to specify between this overloaded DSP toolbox function and the third-party Chronux toolbox function, especially since `builtin()` doesn't work since the Digital Signal Processing toolbox functions don't count as "built-in" to MATLAB.

I asked Caroline, and she mentioned a quick imperfect fix: search the result of `which findpeaks` for the word "chronux", and then, based on that result, reformulate the call to findpeaks based on if Chronux' `findpeaks()` is overloading the DSP one. Theoretically, for a similar reason as above, **this may cause the DSP to stop working correctly if we use other DSP functions that depend on the DSP-specific `findpeaks()`**...but I don't yet know a better solution. 

IF we could find a way to install Chronux such that we were required to include the namespace when using the function, like `chronux.findpeaks()`, then that should completely solve our problem.

**Comment by asoplata** [comment]
Good news everyone! I've found another hacky solution, but one that DEFINITELY works. Simply, you can turn any MATLAB toolbox, like Chronux into what's called a "package" https://www.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html by

1. Putting the toolbox into a parent directory, e.g. `~/Documents/MATLAB/chronux_parent/chronux` where the last folder is where all the Chronux code is stored
2. Simply add plus signs `+` to the beginning of every folder name in the toolbox! So `~/Documents/MATLAB/chronux_parent/chronux/spectral_analysis/continuous/findpeaks.m` becomes `~/Documents/MATLAB/chronux_parent/+chronux/+spectral_analysis/+continuous/findpeaks.m` 
3. Done! Now you can call Chronux' version of `findpeaks()` ONLY by

```{matlab}
chronux.spectral_analysis.continuous.findpeaks()
```

And if you run `which findpeaks`, you get the DSP copy, not the Chronux copy.

This is a cumbersome method, however, since 

1. You need to rename every folder in the toolbox, and
2. In order for the toolbox's functions to refer to each other, now THEY too must be namespaced, i.e. if another Chronux function needs Chronux' `findpeaks()`, you have to change the code of that parent function to use `chronux.spectral_analysis.continuous.findpeaks()`, NOT just `findpeaks()`. This, of course, is possible to do, but requires inline code replacement that can understand relative folder locations of other functions.

At the end of the day, though, you know what would be the best solution? Just freaking renaming `findpeaks` in the Chronux toolbox to be something else, and find/replacing all Chronux usage of that function with whatever the new name is. I think the complexity involved in working around this warrants that we should consider "contributing upstream" and asking the Chronux people to consider renaming the function maybe (or asking MATLAB to rename theirs).
