### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#33]
How exactly a reference to DynaSim should appear in a manuscript?

Up-to-date citation:

Sherfey JS, and Contributors (2016) DynaSim toolbox for modeling and simulating dynamical systems. https://github.com/DynaSim

or

Sherfey JS, & Contributors (2016) DynaSim toolbox for modeling and simulating dynamical systems. https://github.com/DynaSim

**Comment by kupiqu** [comment]
What I am using right now:

`Sherfey JS (2016) DynaSim toolbox for modeling and simulating dynamical systems. https://github.com/DynaSim`

**Comment by asoplata** [comment]
Don't sell yourself short Salva! I would put Sherfey and "Contributors"
since you also wrote code that went into DynaSim.

IIRC, oftentimes science software projects don't list every single person
who's contributed to code in the "authorship", but instead have a single
CONTRIBUTORS.md file in the repo that lists everyone who's contributed.


--
Austin E Soplata
Graduate Program for Neuroscience,
Boston University
L - linkedin.com/in/*austinsoplata*
<http://www.linkedin.com/in/austinsoplata>
P - 901 486 9833
T -  @austinsoplata <https://twitter.com/austinsoplata>

**Comment by kupiqu** [comment]
It sounds good to me. I'll update the citation above, and will modify it according to what we agree on...

**Comment by asoplata** [comment]
There's actually a big paper that just came out on software citation in research https://peerj.com/articles/cs-86/

**Comment by erik-roberts** [comment]
What got decided for this?

**Comment by asoplata** [comment]
Jason recently told me to cite it as the most recent poster presentation of it:

Sherfey JS. (2016). DynaSim: a Matlab toolbox for rapidly building and exploring neural models. 2016 Janelia conference on Collaborative Development of Data-Driven Models of Neural Systems, Ashburn, Virginia.

Where the poster itself is [at here](http://jasonsherfey.com/wp-content/uploads/2017/04/2016_Janelia_poster_JasonSherfey-FINAL.pdf)

This is probably the best choice until the DynaSim paper itself comes out.

**Comment by benpolletta** [comment]
Since the paper is imminent, I'm gonna close this.
