### ISSUE TITLE
function namespacing

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#46]
perhaps functions can be renamed with a dynasim prefix, like dsPlotData instead of PlotData, to avoid issues like with #31

**Comment by asoplata** [comment]
I think that, if there is a naming conflict by a function of our creation, we should just rename our function to something different so that there are no overlaps. As far as I'm aware, DynaSim so far has not produced any functions where this has been an issue - `findpeaks()` in #31 is NOT due to a DynaSim-titled function, but rather a conflict between the Chronux toolbox and MATLAB's Signal Processing Toolbox.

**Comment by erik-roberts** [comment]
#145

**Comment by erik-roberts** [comment]
issues:

dbstack uses the function name without the package. this is workable when using a single package, but inwieldy with multiple packages or sub packages.
have to call every function as ds.function, so lots of code had to be changed. might be nice to use a ds class so one doesn't have to do that.
implementing a ds class would avoid these issues.

**Comment by erik-roberts** [comment]
after removing packages this is no longer an issue
