### ISSUE TITLE
dsPlot rates not working

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#464]
`'plot_type', 'rates'`

**Comment by asoplata** [comment]
I tried to debug this and it seems the issue is that "dat" is not set for the rates "case". Under each of the enumerated scenarios (how many figs, etc.), the core data "dat" is never assigned during the case of 'plot_type', 'rates'.

I'm only 90% convinced that's the issue, though, since I could SWEAR it worked last week for me during testing. It may only be working for certain edge cases.

Regardless, a "case" entry in the major enumerated list of `dsPlot.m` is needed, and will likely fix this.

**Comment by davestanley** [comment]
Out of curiosity did you try it in dsplot2? Last I checked it was working.
I believe the options to pass to plot_type are meanFR and heatmapFR (look
at the checkoptions varargin line to be sure).

**Comment by erik-roberts** [comment]
duplicate #43
