### ISSUE TITLE
independent_solve_file_flag

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#495]
Goal: make the solve files as independent as possible, so that one doesnt need DS anymore once it's been generated

problem: right now, you still need dsSimulate to rerun the file and get a DS data structure

solution: solve file returns a DS data strcture.
- for solve file, instead of a list of output variables, have output variables go into a structure as dsSimulate normally does. this makes it easier when using the solve file independently.
- add other stuff like model field from a mat file

advantage: speeding up re runs. all you have to do is change the params.mat file then and rerun. we could even have an easy gui for that

**Comment by jsherfey** [comment]
Potential problems with doing that:
1. If the structure is defined at the end of the solve_file, then double
the memory is required (i.e., once for the variable and once for the field
storing the variable).
2. If state variables are initialized in the solve_file as fields of a
structure, then the solve_file integration code block would become less
readable (i.e., the structure and "." would be prepended to all variables).
3. State variables are saved in the MAT-file as separate variables so that
the data structure can be obtained using: `data=load(datafile)` and so that
subsets of state variables can be loaded without loading the entire data
set. The state variables would have to be extracted from the structure in
`dsSimulate` before saving if they were already stored in a structure.
This, too, could double the memory required.

**Comment by erik-roberts** [comment]
1 and 2 are mutually exclusive. I'm going with 1 since it's easier to write and maintain and remove if desired. Also, memory continues to grow every year.

1. yes, that's why this won't be the default option.
2. yes, true.
3. two situations: a) using dsSimulate; b) using solve file alone.
  a. i wrote it so dsSimulate acts as normal and won't tell a difference.  it just has to do less formatting of the data since the returned data structure from feval is already solid.
  b. the solve file just returns a data structure. saving would be handled by the user if desired. the splitting of the structure is automatically done by matlab using: `save(filename, '-struct','data')`

**Comment by jsherfey** [comment]
I think that's ok as long as the default behavior is the same as before in
every way (i.e., both internally and from the user's perspective) and the
only way to request the output to be a structure is by setting a new option
in `dsSimulate`.

**Comment by erik-roberts** [comment]
if using options.mex_flag, coder won't let one load metadata file, so it is done in dsSimulate as normal.  thus, running the mex file alone would produce most of a DS data struct, but missing the contents of metadata.mat. a wrapper function could be used to deal with this.

**Comment by erik-roberts** [comment]
still need to implement for parfor mode
