### ISSUE TITLE
dsPlot raster changes

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#507]
1) change color to blue to avoid as much conflict with text. also follows color of waveform.
2) remove final population line separator that sits at top needlessly
3) reverse y axis so first pop on top

**Comment by davestanley** [comment]
I'm removing the y-axis inversion, because this creates issues with overlaid plots. See issue #529 and related commit 6653b07.

I'm also switching the rastergram color back to black with commit 49bee6bc97b5015033fcd91f0690e9d0dbd781ac, since black shows up better in paper figures. Feel free to revert if this is problematic.

**Comment by davestanley** [comment]
Re-opening this issue to address point number 3 above (reverse y axis so first pop on top).

I've added commit 755fbd8834f1c0fbead9c8b5abc247ba388f1eb6, which now causes dsPlot's rastergram mode to draw the rastergram cells from top-to-bottom instead of bottom-to-top. Thus, populations appear in the correct order with the first population on top (e.g., matching the ordering that would appear for waveform plots).

This has essentially the same effect as the operation `set(thisAxes,'ydir','reverse');` in commit 88460b1a7e66375a5df85b17a33fe4e790c997d9, except the axis is not inverted, and thus does not create problems like those documented in #529.
