### ISSUE TITLE
No check for incorrect vary parameter names

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#71]
SimulateStudy seems to let one try to vary over a parameter that doesn't exist (eg spelled wrong), without throwing an error.

**Comment by jsherfey** [comment]
This is intentional behavior. It is useful for varying dummy parameters; for instance, a counter for running multiple realizations with stochastic differential equations.

Example: 10 realizations of HH neuron with noisy drive:
dsPlot(dsSimulate('dv/dt=10+@current+randn; {iNa,iK}','vary',{'counter',1:10}));

**Comment by erik-roberts** [comment]
in that case, the counter would be instantiated in the equations as `counter = 0` and then vary it.

**Comment by jsherfey** [comment]
If the parameter "counter" is not defined anywhere, it would be set to 1,
then 2, then 3, etc, and would not be used in the equations at all.

**Comment by erik-roberts** [comment]
> If the parameter "counter" is not defined anywhere, it would be set to 1, then 2, then 3, etc, and would not be used in the equations at all.

to clarify, what is meant is that if we add checking that throws an error, the way to avoid the error with a dummy counter should be to instantiate it in the equations, and then vary it. that way, it has been declared for ds to recognize it and not throw the error.

**Comment by jsherfey** [comment]
Can you describe an example/situation that would throw an error?



On Dec 7, 2017 10:49 AM, "Erik A. Roberts" <notifications@github.com> wrote:

If the parameter "counter" is not defined anywhere, it would be set to 1,
then 2, then 3, etc, and would not be used in the equations at all.

to clarify, what is meant is that if we add checking that throws an error,
the way to avoid the error with a dummy counter should be to instantiate it
in the equations, and then vary it. that way, it has been declared for ds
to recognize it and not throw the error.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/DynaSim/DynaSim/issues/71#issuecomment-350007789>, or mute
the thread

**Comment by erik-roberts** [comment]
> to clarify, what I meant is that if we add checking that throws an error, the way to avoid the error with a dummy counter should be to instantiate it in the equations, and then vary it. that way, it has been declared for ds to recognize it and not throw the error.

The lack of throwing an error is the exact problem for #296. In the last comment, I was speaking hypothetically from the viewpoint of once we implement #296, how one would deal with a dummy variable—that's all.
