### ISSUE TITLE
Add parameters at sim time not in mech files

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#91]
sometimes i want to assign parameters to strings with function calls, and make new variables not found in the original mech file.  it would be nice if DS would find those new parameters that get stored in modifications and add them to the base model and param file.

**Comment by erikthered12** [comment]
problem: importmodel is called to make modifications from populations/connections.parameters and vary.  In both situations, the corresponding mechanism is not clear, since there can be a list of mechanisms.  consider new naming convention with prepended cell describing the index of the mech for modifications to apply to.

**Comment by jsherfey** [comment]
Parameters specified in spec.*.parameters are now added to spec.pops.equations in dsCheckSpecification(). Mechanism-specific parameters to vary can be specified using e.g., {'pop.mech','param',values}.

**Comment by erik-roberts** [comment]
@jsherfey is this documented on the wiki or in the dev branch? i dont see it in the debug branch at least.
